apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx
        image: my-custom-nginx:latest  # Usa la imagen local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-3
spec:
  selector:
    app: nginx3
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
      name: http
  type: NodePort
