# Usa la imagen base oficial de nginx
FROM nginx:latest

# Copia el archivo HTML al directorio predeterminado de NGINX
COPY ./index.html /usr/share/nginx/html/index.html

# Expone el puerto 80 para acceder a NGINX
EXPOSE 80
