apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: myuser  # Cambia el nombre de usuario si lo deseas
        - name: POSTGRES_DB
          value: mydatabase  # Cambia el nombre de la base de datos si lo deseas
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            memory: "512Mi"  # Solicitud mínima de memoria
            cpu: "50m"      # Solicitud mínima de CPU
          limits:
            memory: "1Gi"    # Límite máximo de memoria
            cpu: "1"         # Límite máximo de CPU
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
